### ISSUE TITLE
Main: File Structure

### ISSUE THREAD

**Issue by hwangyena** [Numble3/admin#8]
페이지 내의 폴더는 전부 페이지를 띄우는 요소들로만 이루어져있습니다.
`pages > main > video.tsx` 파일은 `components > main` 으로 이동하는게 좋을 것 같아요! 

(자세한 React File Structure는 이 [블로그](https://smoh.tistory.com/385)를 참고하시면 좋을 것 같아요!  현재 폴더 구조는 블로그에서 설명하는 2번 구조입니다)

**Comment by suu3** [comment]
감사합니다! 참고용 블로그까지😍 저번에 타입 말씀해주신 거랑 수정해서 pr 올릴게요!
